---
title: "Start TaxFam Project"
author: admin
date: 2023-09-15
categories: ["R"]
tags: ["Tax Design", "Family Dynamics"]
---


September 16th 2023 marks the start of our ARC (Action de Recherche Concertée) project TaxFam. TaxFam stands for Tax Design and Family Dynamics. During the coming 5 years, we will study the interaction between the fiscal system and the structure of Belgian households. The project mobilizes expertise in public economics, econometrics and fiscal law, and focuses on 3 main axes: 
- The fiscal unit. What is the principal fiscal unit: the individual or the household? What are the consequences of a further individualization of taxation? And what is a fair/optimal division of the tax burden between singles and couples?  
- The costs of children. What impact does the fiscal treatment of the costs of raising children have on the households with children? How does this affect the labor market participation of the second earner in households?  
- Divorce. How does the fiscal treatment of divorced couples and alimony payments affect intra-household behavior, such as intra-household specialisation or labor market participation? And how does it affect divorce rates?  